name: 'Deploy the site to an S3 bucket'
description: 'Deploy a static website via S3'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket to deploy to'
    required: false
    default: 'us-east-1'
    

  dist-folder:
    description: 'The folder containing the deployable files'
    required: true

outputs:
  deploy-url:
    description: 'The URL of the deployed site'

runs:
  using: 'node16'
  main: 'main.js'
